INSERT INTO [dbo].[CardType]
VALUES
('Abominable Bowman', 7, 6, 7, 'fa-rocket'),
('Acherus Veteran', 1, 2, 1, 'fa-rocket'),
('Acholyte of Agony', 3, 3, 3, 'fa-rocket'),
('Animated Berserk', 1, 1, 3, 'fa-rocket'),
('Archbishop Benedictus', 7, 4, 6, 'fa-rocket'),
('Arfus', 4, 2, 2, 'fa-rocket'),
('Arrogant Crusader', 4, 5, 2, 'fa-rocket'),
('Bearshark', 3, 4, 3, 'fa-rocket'),
('Blackguard', 6, 3, 9, 'fa-rocket'),
('Blood-Queen LanaThel', 5, 1, 6, 'fa-rocket'),
('Blood Razor', 4, 2, 2, 'fa-rocket'),
('Bloodwrom', 5, 4, 4, 'fa-rocket'),
('Bolvar, Fireblood', 5, 1, 7, 'fa-taxi'),
('Bone Baron', 5, 5, 5, 'fa-taxi'),
('Bone Drake', 6, 6, 5, 'fa-taxi'),
('Bonemare', 7, 5, 5, 'fa-taxi'),
('Brrrloc', 2, 2, 2, 'fa-taxi'),
('Chillblade Champion', 4, 3, 2, 'fa-taxi'),
('Cobalt Scalebane', 5, 5, 5, 'fa-taxi'),
('Coldwraith', 5, 3, 4, 'fa-taxi'),
('Corpse Raiser', 5, 3, 3, 'fa-taxi'),
('Corpse Widow', 5, 4, 6, 'fa-taxi'),
('Corpsetaker', 4, 3, 3, 'fa-taxi'),
('Crypt Lord', 3, 1, 6, 'fa-taxi'),
('Deadscale Knight', 1, 1, 1, 'fa-taxi'),
('Death Revenant', 5, 3, 3, 'fa-snowflake-o'),
('Deathaxe Punisher', 4, 3, 3, 'fa-snowflake-o'),
('Deathspeaker', 3, 2, 4, 'fa-snowflake-o'),
('Despicable Dreadlord', 5, 4, 5, 'fa-snowflake-o')
INSERT INTO [dbo].[CardType]
VALUES
('Doomed Apprentice', 3, 3, 2, 'fa-snowflake-o'),
('Drakkari Defender', 3, 2, 8, 'fa-snowflake-o'),
('Drakkari Enchanter', 3, 1, 5, 'fa-snowflake-o'),
('Druid of the Swarm', 2, 1, 2, 'fa-snowflake-o'),
('Rotface', 8, 4, 6, 'fa-snowflake-o'),
('Exploding Bloatbat', 4, 2, 1, 'fa-snowflake-o'),
('Fallen Sun Cleric', 2, 2, 1, 'fa-snowflake-o'),
('Fatespinner', 5, 5, 3, 'fa-snowflake-o'),
('Furnacefire Colossus', 6, 6, 6, 'fa-trophy'),
('Ghastly Conjurer', 4, 2, 6, 'fa-trophy'),
('Gnomeferatu', 2, 2, 3, 'fa-trophy'),
('Grave Shambler', 4, 4, 4, 'fa-trophy'),
('Grim Necromancer', 4, 2, 4, 'fa-trophy'),
('Hadronox', 9, 3, 7, 'fa-trophy'),
('Happy Ghoul', 3, 3, 3, 'fa-trophy'),
('Howlfiend', 3, 3, 6, 'fa-trophy'),
('Howling Commander', 3, 2, 2, 'fa-trophy'),
('Hyldnir Frostrider', 3, 4, 4, 'fa-trophy'),
('Ice Breaker', 3, 1, 3, 'fa-trophy'),
('Ice Walker', 2, 1, 3, 'fa-trophy'),
('Keening Banshee', 4, 5, 5, 'fa-trophy'),
('Lights Sorrow', 4, 1, 4, 'fa-trophy'),
('Lilian Voss', 4, 4, 5, 'fa-trophy'),
('Meat Wagon', 4, 1, 4, 'fa-trophy'),
('Mindbreaker', 3, 2, 5, 'fa-trophy'),
('Moorabi', 6, 4, 4, 'fa-trophy'),
('Mountaifire Armor', 3, 4, 3, 'fa-trophy'),
('Necrotic Geist', 6, 5, 3, 'fa-trophy'),
('Nerubian Unraveler', 6, 5, 5, 'fa-trophy'),
('Night Howler', 4, 3, 4, 'fa-trophy'),
('Obsidian Statue', 9, 4, 8, 'fa-trophy'),
('Phantom Freebooter', 4, 3, 3, 'fa-rocket'),
('Plague Scientist', 3, 2, 3, 'fa-rocket'),
('Prince Keleseth', 2, 2, 2, 'fa-rocket'),
('Prince Taldaram', 3, 3, 3, 'fa-rocket'),
('Prince Valanar', 4, 4, 4, 'fa-rocket'),
('Professor Putricide', 4, 5, 4, 'fa-rocket'),
('Rattling Rascal', 4, 2, 2, 'fa-rocket'),
('Righteous Protector', 1, 1, 1, 'fa-rocket'),
('Runeforge Haunter', 4, 5, 3, 'fa-rocket'),
('Sanguine Reveler', 1, 1, 1, 'fa-rocket'),
('Saronite Chain Gang', 4, 2, 3, 'fa-rocket'),
('Shadow Ascendant', 2, 2, 2, 'fa-rocket'),
('Shadowblade', 3, 3, 2, 'fa-rocket'),
('Shallow Gravedigger', 3, 3, 1, 'fa-rocket'),
('Sindragosa', 8, 8, 8, 'fa-rocket')